version: "3.8"
name: nrarivin-backend-devops
services:
  webserver_backend:
    image: nginx:alpine
    container_name: webserver_backend
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${VOLUMES_DRIVER}:/var/www/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - php-fpm_backend

  php-fpm_backend:
    container_name: php-fpm_backend
    build:
      context: .
      args:
      - VOLUMES_DRIVER=${VOLUMES_DRIVER}
      dockerfile: Dockerfile
    volumes:
      - ${VOLUMES_DRIVER}:/var/www
      - ./docker/php/7.4/php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_DATE_TIMEZONE=Asia/Jakarta
      - PHP_DISPLAY_ERRORS=On
      - PHP_MEMORY_LIMIT=2560M
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    depends_on:
      - cache
    networks:
      - app-network

  cache:
    container_name: cache_backend
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker/cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    networks:
      - app-network

  supervisor_backend:
    container_name: supervisor_backend
    build:
      context: . # Direktori tempat Dockerfile Supervisor berada
      dockerfile: supervisor.Dockerfile # Nama Dockerfile Supervisor yang berbeda
    volumes:
      - ${VOLUMES_DRIVER}:/var/www
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
    driver: bridge
