version: "3.8"
name: nrarivin-backend-devops
services:
  webserver_backend:
    build:
      context: ./docker/nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: nginx:alpine
    container_name: webserver_backend
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${VOLUMES_DRIVER}/:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/certbot/conf/:/etc/nginx/ssl/
      - ./docker/dhparam/:/etc/nginx/dhparam
      - ./docker/certbot/data/:/usr/share/nginx/html/letsencrypt
    networks:
      - app-network
    depends_on:
      - php-fpm_backend

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_backend
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email rio@dimasrio.com --agree-tos --no-eff-email -d centz.dimasrio.com
    volumes:
      - ./docker/certbot/conf/:/etc/letsencrypt
      - ./docker/certbot/logs/:/var/log/letsencrypt
      - ./docker/certbot/data:/usr/share/nginx/html/letsencrypt

  php-fpm_backend:
    container_name: php-fpm_backend
    build:
      context: .
      args:
      - VOLUMES_DRIVER=${VOLUMES_DRIVER}
      - PUID=${PHP_FPM_PUID}
      - PGID=${PHP_FPM_PGID}
      dockerfile: Dockerfile
    volumes:
      - ${VOLUMES_DRIVER}/:/var/www/
      - ./docker/php/7.4/php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_DATE_TIMEZONE=Asia/Jakarta
      - PHP_DISPLAY_ERRORS=On
      - PHP_MEMORY_LIMIT=2560M
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    depends_on:
      - cache
    networks:
      - app-network

  cache:
    container_name: cache_backend
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker/cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    networks:
      - app-network

  supervisor_backend:
    container_name: supervisor_backend
    build:
      context: . # Direktori tempat Dockerfile Supervisor berada
      dockerfile: supervisor.Dockerfile # Nama Dockerfile Supervisor yang berbeda
    volumes:
      - ${VOLUMES_DRIVER}/:/var/www
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
    driver: bridge
